### ISSUE TITLE
agbabi version is outdated

### ISSUE THREAD

**Issue by exelotl** [98devin/ada-gba-dev#27]
agbabi has had some important bugfixes to memcpy and memset over the last year, so would probably be worth updating!

I'm aware of a project that ran into (possibly) memcpy related issues which might be fixed by this:
https://git.sr.ht/~nytpu/petros/tree/master/item/src/rgou-random.adb#L47-49

**Comment by 98devin** [comment]
Thanks for the heads up. It took some fiddling to get my WSL environment back to being able to build this project but I have updated the sources included in the gba runtime to use agbabi 2.1.4 now. I haven't yet done thorough testing.
